# Generated by Django 6.1.1 on 2026-10-04 22:21

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_inventario', models.CharField(max_length=50, unique=True, verbose_name='Código de inventario')),
                ('nombre', models.CharField(max_length=200)),
                ('modelo', models.CharField(blank=True, max_length=200, null=True)),
                ('especificaciones', models.TextField(blank=True, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ubicación')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('prestado', 'Prestado'), ('en_mantenimiento', 'En mantenimiento'), ('fuera_servicio', 'Fuera de servicio')], default='disponible', max_length=20)),
                ('valor_adquisicion', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor de adquisición ($)')),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoría')),
                ('tipo', models.CharField(choices=[('renovable', 'Renovable'), ('perecible', 'Perecible')], default='perecible', help_text='Hallazgo entrevista (Anexo 6, #16): renovable vuelve al stock al devolver', max_length=10)),
                ('cantidad_total', models.PositiveIntegerField(default=0)),
                ('cantidad_disponible', models.PositiveIntegerField(default=0)),
                ('umbral_minimo', models.PositiveIntegerField(default=0, help_text='Aviso de stock bajo cuando cantidad_disponible <= umbral_minimo')),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('estudiante', 'Estudiante'), ('docente', 'Docente'), ('director_carrera', 'Director de Carrera'), ('encargado_laboratorio', 'Encargado de Laboratorio'), ('control_calidad', 'Control de Calidad'), ('comite_ejecutivo', 'Comité Ejecutivo')], default='estudiante', max_length=30, verbose_name='Rol institucional')),
                ('seccion', models.CharField(blank=True, help_text='Para estudiantes (usado en bloqueos RF-09)', max_length=30, null=True)),
                ('bloqueado_hasta', models.DateTimeField(blank=True, help_text='RF-09: fecha hasta la cual el usuario esta bloqueado', null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('falla_descrita', models.TextField(blank=True, null=True)),
                ('costo_cotizado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('porcentaje_costo', models.DecimalField(blank=True, decimal_places=4, help_text='costo_cotizado / valor_adquisicion', max_digits=5, null=True)),
                ('decision', models.CharField(choices=[('reparar', 'Reparar'), ('dar_baja', 'Dar de baja'), ('pendiente', 'Pendiente')], default='pendiente', max_length=10)),
                ('fecha_diagnostico', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='inventario.equipo')),
                ('reportado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'ordering': ['-fecha_diagnostico'],
            },
        ),
        migrations.CreateModel(
            name='Migracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_origen', models.CharField(blank=True, max_length=255, null=True)),
                ('filas_totales', models.PositiveIntegerField(default=0)),
                ('filas_importadas', models.PositiveIntegerField(default=0)),
                ('filas_con_error', models.PositiveIntegerField(default=0)),
                ('detalle_errores', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ejecutado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Migración',
                'verbose_name_plural': 'Migraciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar_uso', models.CharField(choices=[('dentro_sede', 'Dentro de sede'), ('fuera_sede', 'Fuera de sede')], default='dentro_sede', help_text='Hallazgo entrevista #7', max_length=15)),
                ('justificacion', models.TextField(blank=True, null=True, verbose_name='Justificación')),
                ('horario_inicio', models.DateTimeField()),
                ('horario_fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('entregada', 'Entregada'), ('devuelta', 'Devuelta'), ('atrasada', 'Atrasada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=15)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('en_representacion_de', models.ForeignKey(blank=True, help_text='Si el solicitante es docente/director actuando por un estudiante', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_representadas', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrega', 'Entrega'), ('devolucion', 'Devolución')], max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado_equipo', models.CharField(blank=True, help_text='RF-08 / hallazgo #13: condicion al devolver', max_length=20, null=True)),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_responsable', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.solicitud')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Bloqueo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(help_text='Maximo 1 semana segun entrevista (hallazgo #10)')),
                ('motivo', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.solicitud')),
            ],
            options={
                'verbose_name': 'Bloqueo',
                'verbose_name_plural': 'Bloqueos',
            },
        ),
        migrations.CreateModel(
            name='SolicitudItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.equipo')),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.insumo')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.solicitud')),
            ],
            options={
                'verbose_name': 'Ítem de solicitud',
                'verbose_name_plural': 'Ítems de solicitud',
            },
        ),
    ]
